<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-SAUO6O6" failures="1" tests="5" name="com.w2a.API_Batch3.testCases.TestCreateCustomerAPI" time="0.014" errors="0" timestamp="2024-07-02T23:27:11 IST" skipped="4">
  <testcase classname="com.w2a.API_Batch3.testCases.TestCreateCustomerAPI" name="m1" time="0.002">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.w2a.API_Batch3.testCases.TestCreateCustomerAPI.m1(TestCreateCustomerAPI.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- m1 -->
  <testcase classname="com.w2a.API_Batch3.testCases.TestCreateCustomerAPI" name="m1" time="0.002">
    <skipped/>
  </testcase> <!-- m1 -->
  <testcase classname="com.w2a.API_Batch3.testCases.TestCreateCustomerAPI" name="m1" time="0.009">
    <skipped/>
  </testcase> <!-- m1 -->
  <testcase classname="com.w2a.API_Batch3.testCases.TestCreateCustomerAPI" name="m1" time="0.001">
    <skipped/>
  </testcase> <!-- m1 -->
  <testcase classname="com.w2a.API_Batch3.testCases.TestCreateCustomerAPI" name="validateCreateCustomerAPI" time="0.000">
    <skipped/>
  </testcase> <!-- validateCreateCustomerAPI -->
</testsuite> <!-- com.w2a.API_Batch3.testCases.TestCreateCustomerAPI -->
